# Generated by Django 4.2.7 on 2023-11-21 05:46

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('digital', models.BooleanField(default=True, null=True)),
                ('image', Home.models.ResizableImageField(null=True, upload_to='')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
                ('life_expectancy', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Rabbit', 'Rabbit'), ('Birds', 'Birds'), ('Fish', 'Fish'), ('Accessory', 'Accessory')], default='Dog', max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
